<?php
/**
 * @file
 */

/**
 * Human name.
 */
define('MOHA_LIBS', 'Moha Libraries');

/**
 * Machine name.
 */
define('__MOHA_LIBS', 'moha_libs');

/**
 * moha_libs__variables.
 */
define('MOHA_LIBS__VARIABLES', __MOHA_LIBS . '__variables');

/**
 * sites/all/modules/custom/moha/modules/moha_libs
 */
define('MOHA_LIBS__PATH', drupal_get_path('module', __MOHA_LIBS));

/**
 * /sites/all/modules/custom/moha/modules/moha_libs
 */
define('__MOHA_LIBS__PATH', base_path() . MOHA_LIBS__PATH);

/**
 * Implements hook_libraries_info().
 */
function moha_libs_libraries_info() {
  $libraries[__MOHA_LIBS] = array(
    'name' => MOHA_LIBS,
    'library path' => MOHA_LIBS__PATH . '/vendor',
    'version' => '1.0',
    'files' => array(
      'js' => array(),
      'css' => array(),
      'php' => array('autoload.php'),
    ),
  );

  return $libraries;
}
