<?php
/**
 * @file
 */

/**
 * Human name.
 */
define('MOHA_MAILER', 'Moha Mailer');

/**
 * Machine name.
 */
define('__MOHA_MAILER', 'moha_mailer');

/**
 * sites/all/modules/custom/moha/modules/moha_mailer.
 */
define('MOHA_MAILER__PATH', drupal_get_path('module', __MOHA_MAILER));

/**
 * /sites/all/modules/custom/moha/modules/moha_mailer.
 */
define('__MOHA_MAILER__PATH', base_path() . MOHA_MAILER__PATH);

/**
 * Module variables name.
 */
define('MOHA_MAILER__VARIABLES', __MOHA_MAILER. '__variables');

/**
 * Module variables name: moha_mailer__var__manual_to.
 *
 * Reuse mail to data collected from manual sending form.
 */
define('MOHA_MAILER__VARIABLE__MANUAL_TO', __MOHA_MAILER. '__var__manual_to');

/**
 * Module variables name: moha_mailer__var__manual_from.
 *
 * Reuse mail from data collected from manual sending form.
 */
define('MOHA_MAILER__VARIABLE__MANUAL_FROM', __MOHA_MAILER. '__var__manual_from');

/**
 * Implements hook_menu().
 */
function moha_mailer_menu() {
  $items['admin/moha/mailer'] = array(
    'title' => 'Moha Mailer',
    'description' => t('Moha Mail enhancement system.'),
    'page callback' => 'system_admin_menu_block_page',
    'weight' => 10,
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['admin/moha/mailer/dashboard'] = array(
    'title' => 'Moha mailer dashboard',
    'description' => t('Moha mail statistics / dashboard.'),
    'weight' => -99,
    'page callback' => 'drupal_get_form',
    /* @see moha_mailer_dashboard_form() */
    'page arguments' => array('moha_mailer_dashboard_form'),
    'file' => 'moha_mailer.admin.inc',
    'access arguments' => array(MOHA__PERMISSION__ROOT),
  );

  $items['admin/moha/mailer/config'] = array(
    'title' => 'Moha mailer configuration',
    'description' => t('Moha mailer configuration.'),
    'page callback' => 'drupal_get_form',
    /* @see moha_mailer_config_form() */
    'page arguments' => array('moha_mailer_config_form'),
    'file' => 'moha_mailer.admin.inc',
    'access arguments' => array(MOHA__PERMISSION__ROOT),
  );

  $items['admin/moha/mailer/manual'] = array(
    'title' => 'Moha mail manual sending',
    'description' => t('Manual mail sending function.'),
    'page callback' => 'drupal_get_form',
    /* @see moha_mailer_manual_form() */
    'page arguments' => array('moha_mailer_manual_form'),
    'file' => 'moha_mailer.admin.inc',
    'access arguments' => array(MOHA__PERMISSION__ROOT),
  );

  return $items;
}

/**
 * Implements hook_mail().
 *
 * @inheritdoc
 */
function moha_mailer_mail($key, &$message, $params) {
  if (substr($key, 0, 18) === 'moha_mailer_manual') {
    $message['subject'] = $params['subject'];
    $message['body'] = $params['body'];
  }
  else {
    mimemail_mail($key, $message, $params);
  }
}

