<?php
/**
 * @file
 */

/**
 * Human name.
 */
define('MOHA_MAILER', 'Moha Mailer');

/**
 * Machine name.
 */
define('__MOHA_MAILER', 'moha_mailer');

/**
 * sites/all/modules/custom/moha/modules/moha_mailer.
 */
define('MOHA_MAILER__PATH', drupal_get_path('module', __MOHA_MAILER));

/**
 * /sites/all/modules/custom/moha/modules/moha_mailer.
 */
define('__MOHA_MAILER__PATH', base_path() . MOHA_MAILER__PATH);

/**
 * Module variables name.
 */
define('MOHA_MAILER__VARIABLES', __MOHA_MAILER. '__variables');

/**
 * Implements hook_menu().
 */
function moha_mailer_menu() {
  $items['admin/moha/mailer'] = array(
    'title' => 'Moha Mailer',
    'description' => t('Moha Mail enhancement system.'),
    'page callback' => 'system_admin_menu_block_page',
    'weight' => -10,
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['admin/moha/mailer/manual'] = array(
    'title' => 'Moha mailer manual sending',
    'description' => t('Manual mail sending function.'),
    'page callback' => 'drupal_get_form',
    /* @see moha_mailer_manual_form() */
    'page arguments' => array('moha_mailer_manual_form'),
    'access arguments' => array(MOHA__PERMISSION__ROOT),
  );

  return $items;
}

/**
 * Implements hook_mail().
 *
 * @inheritdoc
 */
function moha_mailer_mail($key, &$message, $params) {
  if (substr($key, 0, 18) === 'moha_mailer_manual') {
    $message['subject'] = $params['subject'];
    $message['body'] = $params['body'];
  }
  else {
    mimemail_mail($key, $message, $params);
  }
}

/**
 * Configure storage for uploaded files by CKEditor.
 *
 * @param $form
 *   Nested array of form elements that comprise the form.
 *
 * @param $form_state
 *   A keyed array containing the current state of the form. The arguments
 *   that drupal_get_form() was originally called with are available in the
 *   array $form_state['build_info']['args'].
 *
 * @see \form_builder()
 */
function moha_mailer_manual_form($form, &$form_state) {
  global $language;

  $node = node_load(1);
  $params['subject'] = $node->title;
  $content = node_view($node);
  $params['body'][] = drupal_render($content['body']);
  drupal_mail(__MOHA_MAILER, __FUNCTION__, variable_get('moha_mailer_manual_to'), $language, $params, variable_get('moha_mailer_manual_from'));


//  $params['subject'] = t('Drupal SMTP test e-mail');
//  $params['body'] = array(t('<body>If you receive this message it means your site is capable of using SMTP to send e-mail.</body>'));
//  drupal_mail(__MOHA_MAILER, __FUNCTION__, variable_get('moha_mailer_manual_to'), $language, $params, variable_get('moha_mailer_manual_from'));
}
