<?php
/**
 * @file
 */

/**
 * Human name.
 */
define('MOHA_STYLE', 'Moha Style');

/**
 * Machine name.
 */
define('__MOHA_STYLE', 'moha_style');

/**
 * moha_style__variables.
 */
define('MOHA_STYLE__VARIABLES', __MOHA_STYLE . '__variables');

/**
 * sites/all/modules/custom/moha/modules/moha_style.
 */
define('MOHA_STYLE__PATH', drupal_get_path('module', __MOHA_STYLE));

/**
 * /sites/all/modules/custom/moha/modules/moha_style.
 */
define('__MOHA_STYLE__PATH', base_path() . MOHA_STYLE__PATH);

/**
 * Implements hook_page_build().
 *
 * Includes css to fine tuning html elements.
 */
function moha_style_page_build(&$page) {
  $page['page_bottom']['#attached']['css'][] = MOHA_STYLE__PATH . '/css/moha_style_common.css';

  global $theme_key;

  if (path_is_admin(current_path())) {
    // Fix element style for theme seven.
    if ($theme_key == 'seven') {
      $page['page_bottom']['#attached']['css'][] = MOHA_STYLE__PATH . '/css/moha_style_admin.seven.css';
    }
  }
  else {
    $page['page_bottom']['#attached']['css'][] = MOHA_STYLE__PATH . '/css/moha_style_front.css';
  }
}
