<?php
/**
 * Implements hook_boot().
 */
function moha_boot_boot() {
  global $language;
  global $base_url;

  $exclude_paths = array(
    "moha/user/oauth2/post",
  );

  drupal_load('module', 'user');
  drupal_load('module', 'moha');
  drupal_load('module', 'moha_user');

  global $user;
  if ($user->uid === 1) {
    return;
  }

  $current_page = $_GET['q'];

  if (isset($_SESSION[MOHA_USER__VARIABLE__OAUTH2_INTEGRATION])) {
    return;
  }
}
