<?php
/**
 * @file provides kinds of UI enhansment widget.
 *
 * @URL https://www.drupal.org/docs/7/core/modules/image/working-with-images
 * @URL https://www.drupal.org/node/465230 Posting video from mobile.
 * @URL http://git.blivesta.com/drawer/package-managers/
 * @URL https://github.com/cubiq/iscroll#configuring-the-iscroll
 * @URL https://www.drupal.org/project/drupal/issues/2753457
 * @URL https://www.antimath.info/css/change-throbber-in-drupal-7/
 * @URL https://zhuanlan.zhihu.com/p/26430952 WeUI Uploader with Vue.JS
 * @see https://www.drupal.org/docs/7/api/javascript-api/ajax-forms-in-drupal-7
 * @see https://api.drupal.org/api/drupal/includes%21ajax.inc/group/ajax/7.x
 */

/**
 * Human name.
 */
define('MOHA_UI', 'Moha UI');

/**
 * Machine name.
 */
define('__MOHA_UI', 'moha_ui');

/**
 * sites/all/modules/custom/moha/modules/moha_ui.
 */
define('MOHA_UI__PATH', drupal_get_path('module', __MOHA_UI));

/**
 * /sites/all/modules/custom/moha/modules/moha_ui.
 */
define('__MOHA_UI__PATH', base_path() . MOHA_UI__PATH);

/**
 * Module variables name.
 */
define('MOHA_UI__VARIABLES', __MOHA_UI. '__variables');

/**
 * Implements hook_library().
 */
function moha_ui_library() {
  $libraries[__MOHA_UI] = array(
    'title' => MOHA_UI,
    'website' => 'https://www.moha.online/',
    'version' => '1.0',
    'js' => array(
      MOHA_UI__PATH . '/libs/weui.js/dist/weui.js' => array(),
      MOHA_UI__PATH . '/libs/jquery.rating-stars/dist/js/jquery.rating-stars.js' => array(),
    ),
    'css' => array(
      MOHA_UI__PATH . '/libs/weui/dist/style/weui.css' => array(
        'type' => 'file',
        'media' => 'screen',
      ),
      MOHA_UI__PATH . '/libs/font-awesome/css/font-awesome.css' => array(
        'type' => 'file',
        'media' => 'screen',
      ),
      MOHA_UI__PATH . '/css/moha_ui.css' => array(
        'type' => 'file',
        'media' => 'screen',
      ),
    ),
  );

  return $libraries;
}

/**
 * Implements hook_libraries_info().
 */
function moha_ui_libraries_info() {

  $libraries[__MOHA_UI] = array(
    'name' => MOHA_UI,
    'library path' => MOHA_UI__PATH,
    'version' => '1.0',
    'files' => array(
      'js' => array(
        'libs/weui.js/dist/weui.js',
      ),
      'css' => array(
        'libs/weui/dist/style/weui.css',
        'libs/font-awesome/css/font-awesome.css',
        'css/moha_ui.css',
      ),
      'php' => array(),
    ),
  );

  return $libraries;
}

/**
 * Implements hook_element_info().
 *
 * @see https://www.drupal.org/node/169815
 */
function moha_ui_element_info() {

  $elements = array(
    /* Element: Moha UI - Rating. */
    'moha_ui_rating' => array(
      /* Element carries a value. */
      '#input' => TRUE,
      '#theme' => array('moha_ui_rating'),
    ),

  );

  return $elements;
}

/**
 * Implements hook_theme().
 */
function moha_ui_theme($existing, $type, $theme, $path) {
  $templates = array(
    'moha_ui_rating' => array(
      'template' => 'elements/moha_ui_rating',
      'render element' => 'element',
    ),
    'moha_ui_image_mobile_uploader_widget' => array(
      'render element' => 'element',
    ),
    'moha_ui_image_mobile_uploader_formatter' => array(
      'variables' => array('item' => NULL, 'path' => NULL, 'image_style' => NULL),
    ),
  );

  return $templates;
}

/**
 * Implements hook_field_info().
 *
 * @see https://api.drupal.org/api/drupal/modules!field!field.module/group/field/7.x
 */
function moha_ui_field_info() {

}

/**
 * Implements hook_field_widget_info().
 */
function moha_ui_field_widget_info() {

//  .ajax-progress-throbber
//  .ajax-progress-throbber .message
//  .ajax-progress-throbber .throbber

  $widgets = array(
    'moha_ui_image_mobile_uploader' => array(
      'label' => t('Moha UI: Image Mobile Uploader'),
      'field types' => array('image'),
      'settings' => array(
        /** @see https://www.antimath.info/css/change-throbber-in-drupal-7/ */
        'progress_indicator' => 'toast',
        'preview_image_style' => 'thumbnail',
      ),
      'behaviors' => array(
        'multiple values' => FIELD_BEHAVIOR_CUSTOM,
        'default value' => FIELD_BEHAVIOR_NONE,
      ),
    ),
  );

  return $widgets;
}

/**
 * Implements hook_field_widget_form().
 *
 * @inheritdoc
 */
function moha_ui_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {

  libraries_load(__MOHA_UI);

  switch ($instance['widget']['type']) {
    default:
      return;

    /*  */
    case 'moha_ui_image_mobile_uploader':
      $cardinality = $field['cardinality'];
      $widget = array();

      $elements = image_field_widget_form($form, $form_state, $field, $instance, $langcode, $items, $delta, $element);

      /**
       * #process flow of image elements:
       *
       * @see file_field_widget_process_multiple()
       * @see file_managed_file_process()
       * @see file_field_widget_process()
       * @see image_field_widget_process() changes #theme to image_widget.
       *
       * #theme flow of image elements:
       *
       * @see theme_file_widget_multiple()
       * @see theme_image_widget()
       * @see theme_file()
       */
      foreach (element_children($elements) as $delta) {
        if ($elements[$delta]['#type'] == 'managed_file') {
//          $elements[$delta]['#prefix'] = '<div class="weui-uploader__input-box">';
//          $elements[$delta]['#suffix'] = '</div>';
          $elements[$delta]['#process'][] = 'moha_ui_image_mobile_uploader_widget_process';
        }
      }

      return $elements;
  }

}

/**
 * An element #process callback for the moha_ui_image_mobile_uploader widget.
 *
 * Replace moha_ui_image_mobile_uploader as #theme to render.
 */
function moha_ui_image_mobile_uploader_widget_process($element, &$form_state, $form) {
  $element['#theme'] = 'moha_ui_image_mobile_uploader_widget';
  return $element;
}

/**
 * Returns HTML for a moha_ui_image_mobile_uploader widget.
 *
 * @param $variables
 *   An associative array containing:
 *   - element: A render element representing the image field widget.
 *
 * @see theme_image_widget()
 * @ingroup themeable
 */
function theme_moha_ui_image_mobile_uploader_widget($variables) {
  $element = $variables['element'];
  $output = '';
  $output .= '<div class="image-widget form-managed-file clearfix">';

  if (isset($element['preview'])) {
    $output .= '<div class="image-preview weui-uploader__files">';
    $output .= drupal_render($element['preview']);
    $output .= '</div>';
  }

  $output .= '<div class="image-widget-data">';
  if ($element['fid']['#value'] != 0) {
    $element['filename']['#markup'] .= ' <span class="file-size">(' . format_size($element['#file']->filesize) . ')</span> ';
  }

  if (isset($element['upload'])) {
    $element['upload']['#prefix'] = '<div class="weui-uploader__input-box">';
    $element['upload']['#suffix'] = '</div>';
    $element['upload']['#attributes']['class'][] = 'weui-uploader__input';
  }

  $output .= drupal_render_children($element);
  $output .= '</div>';
  $output .= '</div>';

  return $output;
}

/**
 * Implements hook_field_formatter_info().
 */
function moha_ui_field_formatter_info() {

}

/**
 * Implements hook_webform_component_info().
 */
function moha_ui_webform_component_info() {
  /* Only 16 chars are allowed as Webform component machine name. */
  $components['moha_ui_rating'] = array(
    'label' => t('Moha UI - Rating'),
    'description' => t('Provides Rating field for WebForm.'),
    'features' => array(
      // This component includes an analysis callback. Defaults to TRUE.
      'analysis' => TRUE,

      // Add content to CSV downloads. Defaults to TRUE.
      'csv' => TRUE,

      // This component supports default values. Defaults to TRUE.
      'default_value' => FALSE,

      // This component supports a description field. Defaults to TRUE.
      'description' => FALSE,

      // Show this component in e-mailed submissions. Defaults to TRUE.
      'email' => TRUE,

      // Allow this component to be used as an e-mail FROM or TO address.
      // Defaults to FALSE.
      'email_address' => FALSE,

      // Allow this component to be used as an e-mail SUBJECT or FROM name.
      // Defaults to FALSE.
      'email_name' => TRUE,

      // This component may be toggled as required or not. Defaults to TRUE.
      'required' => TRUE,

      // This component supports a title attribute. Defaults to TRUE.
      'title' => TRUE,

      // This component has a title that can be toggled as displayed or not.
      'title_display' => TRUE,

      // This component has a title that can be displayed inline.
      'title_inline' => TRUE,

      // If this component can be used as a conditional SOURCE. All components
      // may always be displayed conditionally, regardless of this setting.
      // Defaults to TRUE.
      'conditional' => TRUE,

      // If this component allows other components to be grouped within it
      // (like a fieldset or tabs). Defaults to FALSE.
      'group' => FALSE,

      // If this component can be used for SPAM analysis.
      'spam_analysis' => FALSE,

      // If this component saves a file that can be used as an e-mail
      // attachment. Defaults to FALSE.
      'attachment' => FALSE,

      // If this component reflects a time range and should use labels such as
      // "Before" and "After" when exposed as filters in Views module.
      'views_range' => FALSE,

      // Set this to FALSE if this component cannot be used as a private
      // component. If this is not FALSE, in your implementation of
      // _webform_defaults_COMPONENT(), set ['extra']['private'] property to
      // TRUE or FALSE.
      'private' => FALSE,
    ),

    // Specify the conditional behaviour of this component.
    // Examples are 'string', 'date', 'time', 'numeric', 'select'.
    // Defaults to 'string'.
    'conditional_type' => 'numeric',

    'file' => 'webform/components/moha_ui_rating.inc',
  );

  return $components;
}

