<?php
/**
 * @file provides kinds of UI enhansment widget.
 *
 * @URL https://www.drupal.org/docs/7/core/modules/image/working-with-images
 * @URL https://www.drupal.org/node/465230 Posting video from mobile.
 * @URL http://git.blivesta.com/drawer/package-managers/
 * @URL https://github.com/cubiq/iscroll#configuring-the-iscroll
 * @URL https://www.drupal.org/project/drupal/issues/2753457
 * @URL https://www.antimath.info/css/change-throbber-in-drupal-7/
 * @URL https://zhuanlan.zhihu.com/p/26430952 WeUI Uploader with Vue.JS
 * @see https://www.drupal.org/docs/7/api/javascript-api/ajax-forms-in-drupal-7
 * @see https://api.drupal.org/api/drupal/includes%21ajax.inc/group/ajax/7.x
 */

/**
 * Human name.
 */
define('MOHA_UI', 'Moha UI');

/**
 * Machine name.
 */
define('__MOHA_UI', 'moha_ui');

/**
 * sites/all/modules/custom/moha/modules/moha_ui.
 */
define('MOHA_UI__PATH', drupal_get_path('module', __MOHA_UI));

/**
 * /sites/all/modules/custom/moha/modules/moha_ui.
 */
define('__MOHA_UI__PATH', base_path() . MOHA_UI__PATH);

/**
 * Module variables name.
 */
define('MOHA_UI__VARIABLES', __MOHA_UI. '__variables');

/**
 * Implements hook_libraries_info().
 */
function moha_ui_libraries_info() {

  $libraries[__MOHA_UI] = array(
    'name' => MOHA_UI,
    'library path' => MOHA_UI__PATH,
    'version' => '1.0',
    'files' => array(
      'js' => array(
        'libs/weui.js/dist/weui.js',
      ),
      'css' => array(
        'libs/weui/dist/style/weui.css',
        'libs/font-awesome/css/font-awesome.css',
      ),
      'php' => array(),
    ),
  );

  return $libraries;
}

/**
 * Implements hook_element_info().
 *
 * @see https://www.drupal.org/node/169815
 */
function moha_ui_element_info() {

}

/**
 * Implements hook_field_info().
 *
 * @see https://api.drupal.org/api/drupal/modules!field!field.module/group/field/7.x
 */
function moha_ui_field_info() {

}

/**
 * Implements hook_field_widget_info().
 */
function moha_ui_field_widget_info() {

//  .ajax-progress-throbber
//  .ajax-progress-throbber .message
//  .ajax-progress-throbber .throbber

  $widgets = array(
    'moha_ui_image_mobile_uploader' => array(
      'label' => t('Moha UI: Image Mobile Uploader'),
      'field types' => array('image'),
      'settings' => array(
        /** @see https://www.antimath.info/css/change-throbber-in-drupal-7/ */
        'progress_indicator' => 'toast',
        'preview_image_style' => 'thumbnail',
      ),
      'behaviors' => array(
        'multiple values' => FIELD_BEHAVIOR_CUSTOM,
        'default value' => FIELD_BEHAVIOR_NONE,
      ),
    ),
  );

  return $widgets;
}

/**
 * Implements hook_field_widget_form().
 */
function moha_ui_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {

}

/**
 * Implements hook_field_formatter_info().
 */
function moha_ui_field_formatter_info() {

}

/**
 * Implements hook_webform_component_info().
 */
function moha_ui_webform_component_info() {
  $components['moha_ui_star_rating'] = array(
    'label' => t('Moha UI - Star Rating'),
    'description' => t('Star Rating.'),
    'features' => array(
      // This component includes an analysis callback. Defaults to TRUE.
      'analysis' => TRUE,

      // Add content to CSV downloads. Defaults to TRUE.
      'csv' => TRUE,

      // This component supports default values. Defaults to TRUE.
      'default_value' => FALSE,

      // This component supports a description field. Defaults to TRUE.
      'description' => FALSE,

      // Show this component in e-mailed submissions. Defaults to TRUE.
      'email' => TRUE,

      // Allow this component to be used as an e-mail FROM or TO address.
      // Defaults to FALSE.
      'email_address' => FALSE,

      // Allow this component to be used as an e-mail SUBJECT or FROM name.
      // Defaults to FALSE.
      'email_name' => TRUE,

      // This component may be toggled as required or not. Defaults to TRUE.
      'required' => TRUE,

      // This component supports a title attribute. Defaults to TRUE.
      'title' => TRUE,

      // This component has a title that can be toggled as displayed or not.
      'title_display' => TRUE,

      // This component has a title that can be displayed inline.
      'title_inline' => TRUE,

      // If this component can be used as a conditional SOURCE. All components
      // may always be displayed conditionally, regardless of this setting.
      // Defaults to TRUE.
      'conditional' => TRUE,

      // If this component allows other components to be grouped within it
      // (like a fieldset or tabs). Defaults to FALSE.
      'group' => FALSE,

      // If this component can be used for SPAM analysis.
      'spam_analysis' => FALSE,

      // If this component saves a file that can be used as an e-mail
      // attachment. Defaults to FALSE.
      'attachment' => FALSE,

      // If this component reflects a time range and should use labels such as
      // "Before" and "After" when exposed as filters in Views module.
      'views_range' => FALSE,

      // Set this to FALSE if this component cannot be used as a private
      // component. If this is not FALSE, in your implementation of
      // _webform_defaults_COMPONENT(), set ['extra']['private'] property to
      // TRUE or FALSE.
      'private' => FALSE,
    ),

    // Specify the conditional behaviour of this component.
    // Examples are 'string', 'date', 'time', 'numeric', 'select'.
    // Defaults to 'string'.
    'conditional_type' => 'numeric',

    'file' => 'webform/components/moha_ui_star_rating.inc',
  );

  return $components;
}

