<?php
/**
 * @file
 * Provides SMS capability for other Moha modules.
 */
use AlibabaCloud\Client\AlibabaCloud;

/**
 * Human name.
 */
define('MOHA_SMS', 'Moha SMS');

/**
 * Machine name.
 */
define('__MOHA_SMS', 'moha_sms');

/**
 * moha_sms__variables.
 */
define('MOHA_SMS__VARIABLES', __MOHA_SMS . '__variables');

/**
 * sites/all/modules/custom/moha/modules/moha_sms.
 */
define('MOHA_SMS__PATH', drupal_get_path('module', __MOHA_SMS));

/**
 * /sites/all/modules/custom/moha/modules/moha_sms.
 */
define('__MOHA_SMS__PATH', base_path() . MOHA_SMS__PATH);

/**
 * Entity machine name: moha_sms_aliyun_request.
 */
define('__MOHA_SMS_ALIYUN_REQUEST', 'moha_sms_aliyun_request');

/**
 * Entity human name: Moha SMS Aliyun Request.
 */
define('MOHA_SMS_ALIYUN_REQUEST', 'Moha SMS Aliyun Request');

/**
 * Permission: Edit any Moha SMS Aliyun Request.
 */
define('MOHA_SMS__PERMISSION__EDIT_ANY_ALIYUN_REQUEST', 'edit any moha sms aliyun request');

/**
 * Moha SMS URL:
 */
define('MOHA_SMS__URL__SEND', 'admin/moha/sms/send');

/**
 * Moha SMS URL: Moha SMS Aliyun Request management page.
 */
define('MOHA_SMS__URL__ALIYUN_REQUEST_ADMIN_UI', 'admin/moha/entities/sms-aliyun-requests');

/**
 * Moha SMS Aliyun Request Admin UI Filter value: phone.
 */
define('MOHA_SMS_ALIYUN_REQUEST__ADMIN_UI_FILTER__PHONE', __MOHA_SMS_ALIYUN_REQUEST . '__admin_ui_filter__phone');

/**
 * Moha SMS Aliyun Request Admin UI Filter value: receipt_no.
 */
define('MOHA_SMS_ALIYUN_REQUEST__ADMIN_UI_FILTER__RECEIPT_NO', __MOHA_SMS_ALIYUN_REQUEST . '__admin_ui_filter__receipt_no');

/**
 * Judge if user has permission to access Group management page.
 *
 * @param $op
 * @param $entity object
 * @param $account object
 *
 * @return bool
 */
function _moha_sms_entity_admin_access_callback($op, $account = NULL) {
  global $user;

  if (!isset($account)) {
    $account = $user;
  }

  if ($account->uid == 1) {
    return TRUE;
  }

  return FALSE;
}

/**
 * Implements hook_entity_info().
 */
function moha_sms_entity_info() {
  $items = array();

  // Stores basic information of a company / group company.
  // @see: https://www.drupal.org/docs/7/api/entity-api/providing-a-new-entity-type
  $items[__MOHA_SMS_ALIYUN_REQUEST] = moha_define_entity(
    __MOHA_SMS,
    __MOHA_SMS_ALIYUN_REQUEST,
    MOHA_SMS_ALIYUN_REQUEST,
    'MohaSMSAliyunRequest',
    MOHA_SMS__URL__ALIYUN_REQUEST_ADMIN_UI
  );

  return $items;
}

/**
 * Implements hook_menu().
 */
function moha_sms_menu() {
  $items = array();

  $items["admin/moha/sms"] = array(
    'title' => 'Moha SMS',
    'description' => t('Moha SMS module.'),
    'page callback' => 'system_admin_menu_block_page',
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['admin/moha/sms/send'] = array(
    'title' => t('Moha SMS manual sending'),
    'description' => t('SMS single sending page.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_moha_sms_send_form'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['admin/moha/sms/send/%'] = array(
    'title' => t('Moha SMS manual sending'),
    'description' => t('SMS single sending page.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_moha_sms_send_form', 4),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_menu_alter().
 */
function moha_sms_menu_alter(&$items) {
  unset($items[MOHA_SMS__URL__ALIYUN_REQUEST_ADMIN_UI . '/add']);
}

/**
 * Form generation.
 *
 * @param $form
 * @param $form_state
 * @param string $sender
 *
 * @return array
 */
function _moha_sms_send_form($form, &$form_state, $sender = '') {
  $form['phone_no'] = array(
    '#type' => 'textfield',
    '#title' => t('Phone#'),
    '#description' => 'Enter 11-digit cell phone number.',
    '#default_value' => '',
    '#size' => 30,
    '#required' => TRUE,
  );

  $form['receipt_no'] = array(
    '#type' => 'textfield',
    '#title' => t('Receipt#'),
    '#description' => 'Enter 12-digit express receipt number.',
    '#default_value' => '',
    '#required' => TRUE,
  );

  $form['advanced_options'] = array(
    '#type' => 'fieldset',
    '#title' => t('Advanced Options'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );

  $advanced_options = &$form['advanced_options'];

  $advanced_options['bypass'] = array(
    '#type' => 'checkbox',
    '#title' => t('Bypass validation.'),
    '#description' => 'Check to bypass validation of phone# and receipt#',
    '#default_value' => '',
  );

  $form['actions'] = array('#type' => 'actions');
  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Send'),
  );

  return $form;
}

/**
 * Form validation.
 *
 * @param $form
 * @param $form_state
 */
function _moha_sms_send_form_validate($form, &$form_state) {

  $values = $form_state['values'];

  if (!isset($values['bypass']) || $values['bypass'] == 0) {

    $phone_no   = trim($values['phone_no']);
    $receipt_no = trim($values['receipt_no']);

    $mobile_no_format = '/^\d{11}$/';
    $receipt_no_format = '/^\d{12}$/';

    if (!preg_match($mobile_no_format, $phone_no)) {
      form_set_error('phone_no', "Phone number need be 11-digit number.");
    }

    if (!preg_match($receipt_no_format, $receipt_no)) {
      form_set_error('receipt_no', "Receipt number need be 12-digit number.");
    }
  }
}

/**
 * Form submission.
 *
 * @param $form
 * @param $form_state
 */
function _moha_sms_send_form_submit($form, &$form_state) {
  // Download：https://github.com/aliyun/openapi-sdk-php-client
  // Usage：https://github.com/aliyun/openapi-sdk-php-client/blob/master/README-CN.md
  libraries_load(__MOHA_COMPOSER);

  $values = $form_state['values'];

  $phone_no   = trim($values['phone_no']);
  $receipt_no = trim($values['receipt_no']);

  $accessKeyId  = variable_get('aliyunAccessKeyId','');
  $accessSecret = variable_get('aliyunAccessSecret', '');

  $signature = variable_get('aliyunSMSSignature','');
  $template  = variable_get('aliyunSMSTemplate','');


  try {
    AlibabaCloud::accessKeyClient($accessKeyId, $accessSecret)
      ->regionId('cn-hangzhou')
      ->asDefaultClient();

    $template_params = format_string('{"receipt_no":"!receipt_no"}', array('!receipt_no' => $receipt_no));

    $result = AlibabaCloud::rpc()
      ->product('Dysmsapi')
      ->scheme('https') // https | http
      ->version('2017-05-25')
      ->action('SendSms')
      ->method('POST')
      ->options(array(
        'query' => array(
          'RegionId' => 'cn-hangzhou',
          'PhoneNumbers' => $phone_no,
          'SignName' => $signature,
          'TemplateCode' => $template,
          'TemplateParam' => $template_params,
        ),
      ))
      ->request();

    $res = $result->all();

    // Save Aliyun SMS Request.
    global $user;
    $entity_array = $res;
    $entity_array['phone'] = $phone_no;
    $entity_array['template'] = $template;
    $entity_array['params'] = $template_params;
    $entity_array['uid'] = $user->uid;
    $entity = entity_create(__MOHA_SMS_ALIYUN_REQUEST, $entity_array);

    if ($entity) {
      /** @var \MohaSMSAliyunRequestEntity $entity*/
      $entity->save();
    }

    $link = l("history", MOHA_SMS__URL__ALIYUN_REQUEST_ADMIN_UI, array('attributes' => array('target' => '_blank')));

    $severity = WATCHDOG_INFO;
    // Show feedback.
    if ($res['Code'] == 'OK') {
      drupal_set_message('SMS has been sent, check ' . $link . ' to check details.');
    }
    else {
      drupal_set_message(format_string('SMS has not been sent, check !link to check details.', array('!link' => $link)), 'error');
      $severity = WATCHDOG_ERROR;
    }

    // Logs SMS sending result.
    $params = array();
    foreach ($res as $key => $value) {
      $params['%'.$key] = $value;
    }

    watchdog(__FUNCTION__, 'Message: %Message, RequestId: %RequestId, BizId: %BizId, Code: %Code', $params, $severity);

    return;
  }
  catch (Exception $e) {
    moha_show_exception($e);
    watchdog_exception(__FUNCTION__, $e);
  }
}



