<?php

/**
 * Implements hook_install().
 *
 * @throws \FieldException
 */
function moha_saml_install() {
  moha_saml_update_0700();
}

/**
 * Prepares SAML profile2 fields.
 *
 * @throws \FieldException
 *   Field Can't be created and stop update process.
 */
function moha_saml_update_0700() {
  moha_create_profile2(MOHA_SAML);
  moha_create_fields_and_instances('_moha_saml_profile2_fields_and_instances');
}
