<?php
/**
 * @file
 */

/**
 * Human name.
 */
define('MOHA_SAML', 'Moha SAML');

/**
 * Machine name.
 */
define('__MOHA_SAML', 'moha_saml');

/**
 * moha_saml__variables.
 */
define('MOHA_SAML__VARIABLES', __MOHA_SAML . '__variables');

/**
 * sites/all/modules/custom/moha_saml
 */
define('MOHA_SAML__RELATIVE_PATH', drupal_get_path('module', __MOHA_SAML));

/**
 * /sites/all/modules/custom/moha_saml
 */
define('MOHA_SAML__PATH', base_path() . MOHA_SAML__RELATIVE_PATH);

/**
 * Session name of destination
 */
define('MOHA_SAML__SESSION__DESTINATION', __MOHA_SAML . '_session_destination');

/**
 * Implements hook_menu().
 */
function moha_saml_menu() {
  $items['moha/saml/login'] = array(
    'title' => 'Login with SAML',
    'page callback' => 'moha_saml_login',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}



/**
 * Login with SAML information.
 */
function moha_saml_login() {
  global $user;

  try {

    // Reserve destination.
    if (isset($_SERVER['MOHA_SAML__SESSION__DESTINATION'])) {
      $destination = $_SESSION[MOHA_SAML__SESSION__DESTINATION];
    }

    $sso_id = '';
    if (isset($_SERVER['HTTP_SM_UNIVERSALID'])) {
      $sso_id  = $_SERVER['HTTP_SM_UNIVERSALID'];
    }
    elseif (isset($_SERVER['HTTP_USER_SSOID'])) {
      $sso_id = $_SERVER['HTTP_USER_SSOID'];
    }
    elseif (isset($_SERVER['HTTP_UID'])) {
      $sso_id = $_SERVER['HTTP_UID'];
    }

    $mail = '';
    if (isset($_SERVER['HTTP_EMAIL'])) {
      $mail  = $_SERVER['HTTP_EMAIL'];
    }

    if (empty($sso_id)){
      throw new Exception('No SSO in SAML session!');
    }

    if (empty($mail)){
      throw new Exception('No e-mail in SAML session!');
    }

    $user = user_load_by_name(trim($sso_id));

    // If user doesn't exist, create user & profile2.
    if (empty($user)) {
      $password = user_password(32);
      $user_fields = array(
        'name' => $sso_id,
        'pass' => $password,
        'mail' => $mail,
        'status' => 1,
        'timezone' => 'Asia/Shanghai',
        'init' => __FUNCTION__,
        'roles' => array(
          DRUPAL_AUTHENTICATED_RID => 'authenticated user',
        )
      );

      $user = user_save('', $user_fields);

      $profile = profile2_create(array(
        'type' => __MOHA_SAML,
        'uid' => $user->uid
      ));

      $wrapper = entity_metadata_wrapper('profile2', $profile);

      $wrapper->moha_saml_first_name->set($_SERVER['HTTP_FIRST_NAME']);
      $wrapper->moha_saml_last_name->set($_SERVER['HTTP_LAST_NAME']);
      $wrapper->moha_saml_formal_name->set($_SERVER['HTTP_FORMAL_NAME']);
      $wrapper->moha_saml_business_unit->set($_SERVER['HTTP_BUSINESS_UNIT']);
      $wrapper->moha_saml_title->set($_SERVER['HTTP_TITLE']);
      $wrapper->moha_saml_email->set($_SERVER['HTTP_EMAIL']);
      $wrapper->moha_saml_employee_type->set($_SERVER['HTTP_EMPLOYEE_TYPE']);
      $wrapper->save(TRUE);
    }

    // User login.
    $form_state['uid'] = $user->uid;
    user_login_submit(array(), $form_state);
    drupal_session_regenerate();

  }
  catch(Exception $e) {
    // make sure page correctly displayed, so don't throw further.
    watchdog_exception(__FUNCTION__, $e);

    drupal_goto('moha_saml/saml/error');
  }

}

/**
 * Return profile2 fields and instances array for profile2 moha_saml.
 *
 * @return array
 */
function _moha_saml_profile2_fields_and_instances() {

  $saml_field_definitions = array(
    [ 'field_name' => 'moha_saml_sso',           'label' => 'SSO'           ],
    [ 'field_name' => 'moha_saml_first_name',    'label' => 'First name'    ],
    [ 'field_name' => 'moha_saml_last_name',     'label' => 'Last name'     ],
    [ 'field_name' => 'moha_saml_formal_name',   'label' => 'Formal name'   ],
    [ 'field_name' => 'moha_saml_email',         'label' => 'Email'         ],
    [ 'field_name' => 'moha_saml_business_unit', 'label' => 'Business unit' ],
    [ 'field_name' => 'moha_saml_title',         'label' => 'Title'         ],
    [ 'field_name' => 'moha_saml_employee_type', 'label' => 'Employee type' ],
  );

  foreach ($saml_field_definitions as $field_definition) {
    $fields_and_instances[$field_definition['field_name']] = array(
      'type' => 'text',
      'field_name' => $field_definition['field_name'],
      'label' => $field_definition['label'],
      'bundle' => __MOHA_SAML,
      'entity_type' => 'profile2',
      'cardinality' => 1,
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'text',
          'settings' => array(),
          'type' => 'text_default',
          'weight' => 0,
        ),
      ),
      'required' => FALSE,
      'settings' => array(
        'text_processing' => 0,
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'text',
        'settings' => array(
          'size' => 60,
        ),
        'type' => 'text_textfield',
        'weight' => 1,
      ),
    );
  }

  return $fields_and_instances;
}