<?php
/**
 * @file
 * Date: 18/01/2019
 */

// TODO
// Platform information storage entity.

/**
 * Module human name: Moha ITS.
 */
define('MOHA_ITS', 'Moha ITS');

/**
 * Module machine name: moha_its.
 */
define('__MOHA_ITS', 'moha_its');

/**
 * moha_its__variables.
 */
define('MOHA_ITS__VARIABLES', __MOHA_ITS . '__variables');

/**
 * Entity human name: Moha ITS Group.
 */
define('MOHA_ITS_GROUP', 'Moha ITS Group');

/**
 * Entity machine name: moha_its_group.
 */
define('__MOHA_ITS_GROUP', 'moha_its_group');

/**
 * Entity human name: Moha ITS Infrastructure.
 */
define('MOHA_ITS_INFRASTRUCTURE', 'Moha ITS Infrastructure');

/**
 * Entity machine name: moha_its_infrastructure.
 */
define('__MOHA_ITS_INFRASTRUCTURE', 'moha_its_infrastructure');

/**
 * Entity human name: Moha ITS Consumption.
 */
define('MOHA_ITS_CONSUMPTION', 'Moha ITS Consumption');

/**
 * Entity machine name: moha_its_consumption.
 */
define('__MOHA_ITS_CONSUMPTION', 'moha_its_consumption');

/**
 * Entity human name: Moha ITS Department.
 */
define('MOHA_ITS_DEPARTMENT', 'Moha ITS Department');

/**
 * Entity machine name: moha_its_department.
 */
define('__MOHA_ITS_DEPARTMENT', 'moha_its_department');

/**
 * Entity human name: Moha ITS Solution.
 */
define('MOHA_ITS_SOLUTION', 'Moha ITS Solution');

/**
 * Entity machine name: moha_its_solution.
 */
define('__MOHA_ITS_SOLUTION', 'moha_its_solution');

/**
 * Entity human name: Moha ITS Service.
 */
define('MOHA_ITS_SERVICE', 'Moha ITS Service');

/**
 * Entity machine name: moha_its_service.
 */
define('__MOHA_ITS_SERVICE', 'moha_its_service');

/**
 * Entity human name: Moha ITS Effort.
 */
define('MOHA_ITS_EFFORT', 'Moha ITS Effort');

/**
 * Entity machine name: moha_its_effort.
 */
define('__MOHA_ITS_EFFORT', 'moha_its_effort');

/**
 * Entity human name: Moha ITS Status.
 */
define('MOHA_ITS_STATUS', 'Moha ITS Status');

/**
 * Entity machine name: moha_its_status.
 */
define('__MOHA_ITS_STATUS', 'moha_its_status');

/**
 * Permission: Edit any Moha ITS Groups.
 */
define('MOHA_ITS__PERMISSION__EDIT_ANY_GROUP', 'edit any moha its group');

/**
 * Permission: Edit any Moha ITS Infrastructure.
 */
define('MOHA_ITS__PERMISSION__EDIT_ANY_INFRASTRUCTURE', 'edit any moha its infrastructure');

/**
 * Permission: Edit own Moha ITS Groups.
 */
define('MOHA_ITS__PERMISSION__EDIT_OWN_GROUP', 'edit own moha its group');

/**
 * Permission: Edit any Moha ITS Service.
 */
define('MOHA_ITS__PERMISSION__EDIT_ANY_SERVICE', 'edit any moha its service');

/**
 * Permission: Edit any Moha ITS Effort.
 */
define('MOHA_ITS__PERMISSION__EDIT_ANY_EFFORT', 'edit any moha its effort');

/**
 * Moha ITS Group Admin UI Filter value: owner.
 */
define('MOHA_ITS_GROUP__ADMIN_UI_FILTER__OWNER', __MOHA_ITS_GROUP . '__admin_ui_filter__owner');

/**
 * Moha ITS URL: Moha ITS Group management page.
 */
define('MOHA_ITS__URL__GROUP_ADMIN_UI', 'admin/moha/its/groups');

/**
 * Moha ITS URL: Moha ITS Infrastructure management page.
 */
define('MOHA_ITS__URL__INFRASTRUCTURE_ADMIN_UI', 'admin/moha/its/infrastructures');

/**
 * Moha ITS URL: Moha ITS Service management page.
 */
define('MOHA_ITS__URL__SERVICE_ADMIN_UI', 'admin/moha/its/services');

/**
 * Moha ITS URL: Moha ITS Effort management page.
 */
define('MOHA_ITS__URL__EFFORT_ADMIN_UI', 'admin/moha/its/efforts');

/**
 * Moha ITS Vocabulary: Infrastructure types.
 */
define('MOHA_ITS__VOCABULARY__INFRASTRUCTURE_TYPES', 'moha_its__vocabulary__infrastructure_types');

/**
 * Moha ITS Vocabulary: Service types.
 */
define('MOHA_ITS__VOCABULARY__SERVICE_TYPES', 'moha_its__vocabulary__service_types');

/**
 * Moha ITS Vocabulary: Effort types.
 */
define('MOHA_ITS__VOCABULARY__EFFORT_TYPES', 'moha_its__vocabulary__effort_types');

/**
 * Implements hook_entity_info().
 */
function moha_its_entity_info() {
  $items = array();

  // Stores basic information of a company / group company.
  // @see: https://www.drupal.org/docs/7/api/entity-api/providing-a-new-entity-type
  $items[__MOHA_ITS_GROUP] = array(
    'label' => t(MOHA_ITS_GROUP),
    'plural label' => t(MOHA_ITS_GROUP . 's'), // Moha ITS Groups
    'base table' => __MOHA_ITS_GROUP,
    'revision table' => __MOHA_ITS_GROUP . '_revision',
    'entity keys' => array(
      'id' => 'id',
      'label' => 'full_name',
      'revision' => 'vid',
//    'bundle' => 'type',
    ),
    //
    'label callback' => 'entity_class_label',

    /** @see entity_crud_hook_entity_info() */
    "admin ui" => array(
      /* Moha ITS Groups management page URL & Class. */
      "path" => MOHA_ITS__URL__GROUP_ADMIN_UI,
      "controller class" => "MohaITSGroupEntityAdminController",

      /** @see entity_ui_get_form() */
      /* Moha ITS Groups add / edit forms containing file. */
      "file" => "includes/MohaITSGroupEntity.form.inc",  //
    ),

    // Declares which module contains related Class information, like Admin UI Class, etc.
    "module" => __MOHA_ITS,

    "access callback" => "_moha_its_group_entity_admin_access_callback",

    'entity class' => 'MohaITSGroupEntity',
    'controller class' => 'MohaITSGroupEntityController',
    // Uses defaultUri method of entity class to generate entity URL.
    'uri callback' => 'entity_class_uri',

    // Make entity fieldable; @see field_attach_form to attach added fields.
    'fieldable' => TRUE,
    'bundles' => array(
      __MOHA_ITS_GROUP => array(
        'label' => t(MOHA_ITS_GROUP),
        'plural label' => t(MOHA_ITS_GROUP . 's'),
        'admin' => array(
          'path' => MOHA_ITS__URL__GROUP_ADMIN_UI,
          'access arguments' => array(MOHA_ITS__PERMISSION__EDIT_ANY_GROUP),
        ),
      ),
    ),
//    'bundle keys' => array(
//      'bundle' => 'type',
//    ),

    // Views support.
    'views controller class' => 'EntityDefaultViewsController',
  );

  $items[__MOHA_ITS_INFRASTRUCTURE] = array(
    'label' => t(MOHA_ITS_INFRASTRUCTURE),
    'plural label' => t(MOHA_ITS_INFRASTRUCTURE . 's'), // Moha ITS Groups
    'base table' => __MOHA_ITS_INFRASTRUCTURE,
    'revision table' => __MOHA_ITS_INFRASTRUCTURE . '_revision',
    'entity keys' => array(
      'id' => 'id',
      'label' => 'full_name',
      'revision' => 'vid',
    ),
    //
    'label callback' => 'entity_class_label',

    /** @see entity_crud_hook_entity_info() */
    "admin ui" => array(
      /* Moha ITS Infrastructure management page URL & Class. */
      "path" => MOHA_ITS__URL__INFRASTRUCTURE_ADMIN_UI,
      "controller class" => "MohaITSInfrastructureEntityAdminController",

      /** @see entity_ui_get_form() */
      /* Moha ITS Infrastructure add / edit forms containing file. */
      "file" => "includes/MohaITSInfrastructureEntity.form.inc",  //
    ),

    // Declares which module contains related Class information, like Admin UI Class, etc.
    "module" => __MOHA_ITS,

    "access callback" => "_moha_its_group_entity_admin_access_callback",

    'entity class' => 'MohaITSInfrastructureEntity',
    'controller class' => 'MohaITSInfrastructureEntityController',
    // Uses defaultUri method of entity class to generate entity URL.
    'uri callback' => 'entity_class_uri',

    // Make entity fieldable; @see field_attach_form to attach added fields.
    'fieldable' => TRUE,
    'bundles' => array(
      __MOHA_ITS_INFRASTRUCTURE => array(
        'label' => t(MOHA_ITS_INFRASTRUCTURE),
        'plural label' => t(MOHA_ITS_INFRASTRUCTURE . 's'),
        'admin' => array(
          'path' => MOHA_ITS__URL__INFRASTRUCTURE_ADMIN_UI,
          'access arguments' => array(MOHA_ITS__PERMISSION__EDIT_ANY_INFRASTRUCTURE),
        ),
      ),
    ),

    // Views support.
    'views controller class' => 'EntityDefaultViewsController',
  );

  $items[__MOHA_ITS_SERVICE] = array(
    'label' => t(MOHA_ITS_SERVICE),
    'plural label' => t(MOHA_ITS_SERVICE . 's'), // Moha ITS Groups
    'base table' => __MOHA_ITS_SERVICE,
    'revision table' => __MOHA_ITS_SERVICE . '_revision',
    'entity keys' => array(
      'id' => 'id',
      'label' => 'full_name',
      'revision' => 'vid',
    ),
    //
    'label callback' => 'entity_class_label',

    /** @see entity_crud_hook_entity_info() */
    "admin ui" => array(
      /* Moha ITS Groups management page URL & Class. */
      "path" => MOHA_ITS__URL__SERVICE_ADMIN_UI,
      "controller class" => "MohaITSServiceEntityAdminController",

      /** @see entity_ui_get_form() */
      /* Moha ITS Groups add / edit forms containing file. */
      "file" => "includes/MohaITSServiceEntity.form.inc",  //
    ),

    // Declares which module contains related Class information, like Admin UI Class, etc.
    "module" => __MOHA_ITS,

    "access callback" => "_moha_its_group_entity_admin_access_callback",

    'entity class' => 'MohaITSInfrastructureEntity',
    'controller class' => 'MohaITSInfrastructureEntityController',
    // Uses defaultUri method of entity class to generate entity URL.
    'uri callback' => 'entity_class_uri',

    // Make entity fieldable; @see field_attach_form to attach added fields.
    'fieldable' => TRUE,
    'bundles' => array(
      __MOHA_ITS_SERVICE => array(
        'label' => t(MOHA_ITS_SERVICE),
        'plural label' => t(MOHA_ITS_SERVICE . 's'),
        'admin' => array(
          'path' => MOHA_ITS__URL__SERVICE_ADMIN_UI,
          'access arguments' => array(MOHA_ITS__PERMISSION__EDIT_ANY_SERVICE),
        ),
      ),
    ),

    // Views support.
    'views controller class' => 'EntityDefaultViewsController',
  );

  $items[__MOHA_ITS_EFFORT] = array(
    'label' => t(MOHA_ITS_EFFORT),
    'plural label' => t(MOHA_ITS_EFFORT . 's'), // Moha ITS Groups
    'base table' => __MOHA_ITS_EFFORT,
    'revision table' => __MOHA_ITS_EFFORT . '_revision',
    'entity keys' => array(
      'id' => 'id',
      'label' => 'title',
      'revision' => 'vid',
    ),
    //
    'label callback' => 'entity_class_label',

    /** @see entity_crud_hook_entity_info() */
    "admin ui" => array(
      /* Moha ITS Operation management page URL & Class. */
      "path" => MOHA_ITS__URL__EFFORT_ADMIN_UI,
      "controller class" => "MohaITSEffortEntityAdminController",

      /** @see entity_ui_get_form() */
      /* Moha ITS Operation add / edit forms containing file. */
      "file" => "includes/MohaITSEffortEntity.form.inc",  //
    ),

    // Declares which module contains related Class information, like Admin UI Class, etc.
    "module" => __MOHA_ITS,

    "access callback" => "_moha_its_group_entity_admin_access_callback",

    'entity class' => 'MohaITSEffortEntity',
    'controller class' => 'MohaITSEffortEntityController',
    // Uses defaultUri method of entity class to generate entity URL.
    'uri callback' => 'entity_class_uri',

    // Make entity fieldable; @see field_attach_form to attach added fields.
    'fieldable' => TRUE,
    'bundles' => array(
      __MOHA_ITS_EFFORT => array(
        'label' => t(MOHA_ITS_EFFORT),
        'plural label' => t(MOHA_ITS_EFFORT . 's'),
        'admin' => array(
          'path' => MOHA_ITS__URL__EFFORT_ADMIN_UI,
          'access arguments' => array(MOHA_ITS__PERMISSION__EDIT_ANY_EFFORT),
        ),
      ),
    ),

    // Views support.
    'views controller class' => 'EntityDefaultViewsController',
  );

  return $items;
}

/**
 * Implements hook_menu().
 */
function moha_its_menu() {
  $items["admin/moha/its"] = array(
    'title' => 'Moha ITS',
    'description' => t('Moha IT Steward.'),
    'page callback' => 'system_admin_menu_block_page',
    'weight' => -10,
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Judge if user has permission to access Group management page.
 *
 * @param $op
 * @param $entity object
 * @param $account object
 *
 * @return bool
 */
function _moha_its_group_entity_admin_access_callback($op, $entity = NULL, $account = NULL) {
  global $user;

  if ($user->uid == 1) {
    return TRUE;
  }

  if (user_access(MOHA_ITS__PERMISSION__EDIT_ANY_GROUP, $account)) {
    return TRUE;
  }

  return FALSE;
}

/**
 *
 * @see form_validate_machine_name()
 */
function moha_its_group_entity_exists($value){
  return FALSE;
}

/**
 * Implements hook_permission().
 *
 *
 */
function moha_its_permission() {
  return array(
    MOHA_ITS__PERMISSION__EDIT_ANY_GROUP => array(
      'title' => 'Edit Any Moha ITS Group',
    ),
    MOHA_ITS__PERMISSION__EDIT_OWN_GROUP => array(
      'title' => 'Edit Own Moha ITS Group',
    ),
  );
}

/**
 * Returns body field definitions for moha_its_department, moha_its_solution,
 * moha_its_service, moha_its_effort.
 *
 * @return array
 */
function moha_its_fields_and_instances() {
  $types = array(
//    array(
//      'entity' => __MOHA_ITS_DEPARTMENT,
//      'bundle' => __MOHA_ITS_DEPARTMENT,
//    ),
//    array(
//      'entity' => __MOHA_ITS_SOLUTION,
//      'bundle' => __MOHA_ITS_SOLUTION,
//    ),
    array(
      'entity' => __MOHA_ITS_SERVICE,
      'bundle' => __MOHA_ITS_SERVICE,
    ),
    array(
      'entity' => __MOHA_ITS_EFFORT,
      'bundle' => __MOHA_ITS_EFFORT,
    ),
  );

  $fields = moha_generate_description_fields_and_instances($types);

  return $fields;
}
