<?php


/**
 * Human name.
 */
define('MOHA_COMMERCE_ORDER', 'Moha Commerce Order');

/**
 * Machine name.
 */
define('__MOHA_COMMERCE_ORDER', 'moha_commerce_order');

/**
 * moha_commerce_order__variables.
 */
define('MOHA_COMMERCE_ORDER__VARIABLES', __MOHA_COMMERCE_ORDER . '__variables');

/**
 * /sites/all/modules/custom/moha/modules/moha_commerce_order.
 */
define('MOHA_COMMERCE_ORDER__PATH', base_path() . drupal_get_path('module', __MOHA_COMMERCE_ORDER));

/**
 * sites/all/modules/custom/moha/modules/moha_commerce_order.
 */
define('MOHA_COMMERCE_ORDER__RELATIVE_PATH', drupal_get_path('module', __MOHA_COMMERCE_ORDER));

/**
 * Implements hook_menu().
 *
 * Declares configuration page entry, etc.
 */
function moha_commerce_order_menu() {
  $item['admin/moha/commerce/order/config'] = array(
    'title' => 'Moha Commerce Order Configuration',
    'description' => 'Configure order properties and limitations.',
    'type' => MENU_NORMAL_ITEM,
    'weight' => -1,
    'access arguments' => array('administer site configuration'),

    'page callback' => 'drupal_get_form',
    'page arguments' => array('_moha_commerce_order_config_form'),
    'file' => 'includes/moha_commerce_order.admin.inc',
  );

  return $item;
}

/**
 * Implements hook_entity_info().
 */
function moha_commerce_order_entity_info() {
  $items = array();

  // @see: https://www.drupal.org/docs/7/api/entity-api/providing-a-new-entity-type
  $items[__MOHA_COMMERCE_ORDER] = array(
    'label' => t(MOHA_COMMERCE_ORDER),
    'plural label' => t(MOHA_COMMERCE_ORDER . 's'),
    'base table' => __MOHA_COMMERCE_ORDER,
    'entity keys' => array(
      'id' => 'id',
      'label' => 'id',
    ),
    //
    'label callback' => 'entity_class_label',

    // @see entity_crud_hook_entity_info.
    "admin ui" => array(
      "path" => 'admin/moha/commerce/orders',
      "controller class" => "MohaCommerceOrderEntityAdminController",
      "file" => "includes/moha_commerce_order.admin.inc",
    ),
    // Declares which module contains related Class information, like Admin UI Class, etc.
    "module" => __MOHA_COMMERCE_ORDER,

    "access callback" => "_moha_commerce_order_entity_admin_access_callback",

    'entity class' => 'MohaCommerceOrderEntity',
    'controller class' => 'MohaCommerceOrderEntityController',
    // Uses defaultUri method of entity class to generate entity URL.
    'uri callback' => 'entity_class_uri',

    // Make entity fieldable; @see field_attach_form to attach added fields.
    'fieldable' => TRUE,
    'bundles' => array(
      __MOHA_COMMERCE_ORDER => array(
        'label' => t(MOHA_COMMERCE_ORDER),
        'plural label' => t(MOHA_COMMERCE_ORDER . 's'),
        'admin' => array(
          'path' => 'admin/moha/commerce/orders',
          'access arguments' => array('administer moha commerce orders'),
        ),
      ),
    ),

    // Views support.
    'views controller class' => 'EntityDefaultViewsController',
  );

  return $items;
}

/**
 * Implements hook_entity_property_info().
 */
function moha_commerce_order_entity_property_info() {

  $properties['created'] = array(
    'label' => t('Created'),
    'description' => t('Order created date.'),
    'type' => 'date',
    'schema field' => 'created',
  );

  $properties['updated'] = array(
    'label' => t('Updated'),
    'description' => t('Order updated date.'),
    'type' => 'date',
    'schema field' => 'updated',
  );

  $properties['nid'] = array(
    'label' => t('Product'),
    'type' => 'node',
    'bundle' => __MOHA_COMMERCE_PRODUCT,
    'description' => t('Product node ID.'),
    'schema field' => 'nid',
  );

  $properties['oid'] = array(
    'label' => t('Owner'),
    'type' => 'user',
    'description' => t('User ID who requested the order.'),
    'schema field' => 'oid',
  );

  $properties['uid'] = array(
    'label' => t('User'),
    'type' => 'user',
    'description' => t('User ID who made the creation or update.'),
    'schema field' => 'uid',
  );

  $items[__MOHA_COMMERCE_ORDER]['properties'] = $properties;
  return $items;
}



/**
 * @return array
 */
function moha_commerce_order_status_array() {
  return array(
    0 => 'Dropped',
    1 => 'In-use',
    2 => 'Returned',
    3 => 'Transferred',
  );
}

/**
 * @param $op
 * @param $entity object
 * @param $account object
 *
 * @return bool
 */
function _moha_commerce_order_entity_admin_access_callback($op, $entity = NULL, $account = NULL) {
  if (user_access('administer moha commerce order', $account)) {
    return TRUE;
  }

  return FALSE;
}

/**
 * Implements hook_permission().
 */
function moha_commerce_order_permission() {
  return array(
    'administer moha commerce orders' => array(
      'title' => 'Administer Moha Commerce Orders',
    ),
    'create own moha commerce order' => array(
      'title' => 'Create Own Moha Commerce Order',
    ),
  );
}

function moha_commerce_order_entity_info_label($entity, $entity_type) {
  return $entity->id;
}
