<?php
/**
 * @file
 *
 * @link https://www.filamentgroup.com/lab/js-web-fonts.html @endlink
 */

/**
 * Human name.
 */
define('MOHA_FONTS', 'Moha Fonts');

/**
 * Machine name.
 */
define('__MOHA_FONTS', 'moha_fonts');

/**
 * moha_fonts__variables.
 */
define('MOHA_FONTS__VARIABLES', __MOHA_FONTS . '__variables');

/**
 * sites/all/modules/custom/moha/modules/moha_fonts
 */
define('MOHA_FONTS__PATH', drupal_get_path('module', __MOHA_FONTS));

/**
 * /sites/all/modules/custom/moha/modules/moha_fonts
 */
define('__MOHA_FONTS__PATH', base_path() . MOHA_FONTS__PATH);

/**
 * Patch CSS files loading parameters.
 */
define('MOHA_FONTS__PATCH_CSS_LOADING_OPTIONS', array(
  'group' => CSS_THEME,
  'weight' => 999,
));

/**
 * Implements hook_preprocess().
 */
function moha_fonts_preprocess(&$variables, $hook) {

}

/**
 * Implements hook_preprocess_HOOK().
 */
function moha_fonts_preprocess_page(&$variables) {
  // Google fonts local hosting.
  drupal_add_css(MOHA_FONTS__PATH . '/fonts/inconsolata.css', MOHA_FONTS__PATCH_CSS_LOADING_OPTIONS);
  drupal_add_css(MOHA_FONTS__PATH . '/fonts/opensans.css', MOHA_FONTS__PATCH_CSS_LOADING_OPTIONS);
}
