<?php
/**
 * @file
 */

/**
 * Human name.
 */
define('MOHA_ADMIN_MENU', 'Moha Admin Menu');

/**
 * Machine name.
 */
define('__MOHA_ADMIN_MENU', 'moha_admin_menu');

/**
 * sites/all/modules/custom/moha/modules/moha_admin_menu.
 */
define('MOHA_ADMIN_MENU__PATH', drupal_get_path('module', __MOHA_ADMIN_MENU));

/**
 * moha_admin_menu__variable: use non-production admin menu style.
 */
define('MOHA_ADMIN_MENU__VARIABLES__NON_PRD', __MOHA_ADMIN_MENU . '__variable__non_prd');

/**
 * Implements hook_admin_menu_output_build().
 *
 * Invoked before cached in @see admin_menu_output();
 *
 * Leverage logic from @see _custom_menu_toolbar_get_menu_for_current_user().
 */
function moha_admin_menu_admin_menu_output_build(&$content) {

  global $user;
  $user_roles = array_keys($user->roles);

  $menu = db_select('custom_menu_toolbar_role_menus', 'm')
    ->fields('m')
    ->condition('rid', $user_roles, 'IN')
    ->orderBy('weight')
    ->range(0, 1)
    ->execute()
    ->fetchObject();

  if ($menu && $menu->menu_name != '_none') {
    $menu_name = $menu->menu_name;
  }
  else {
    $menu_name = 'management';
  }

  if (function_exists('admin_menu_tree')) {
    $function = 'admin_menu_tree';
  }
  else {
    $function = '_admin_menu_tree';
  }
  if ($user->uid == 1 && $menu_name != 'management') {
    $content['menu'] = admin_menu_links_menu($function('management'));
    $content['menu'][$menu_name] = admin_menu_links_menu($function($menu_name));
    $content['menu'][$menu_name]['#title'] = drupal_ucfirst($menu_name);
  }
  else {
    $content['menu'] = admin_menu_links_menu($function($menu_name));
  }
  $content['menu']['#theme'] = 'admin_menu_links';
  $content['menu']['#wrapper_attributes']['id'] = 'admin-menu-menu';
  // Ensure the menu tree is rendered between the icon and user links.
  $content['menu']['#weight'] = 0;
}

/**
 * Implements @see hook_form_FORM_ID_alter().
 *
 * @see custom_menu_toolbar_menu_settings_form().
 */
function moha_admin_menu_form_custom_menu_toolbar_menu_settings_form_alter(&$form, &$form_state, $form_id) {
  $form_addition['instruction'] = array(
    '#markup' => '<div>' . t(<<<INSTRUCTION
For Custom Menu Toolbar module, when user has multiple roles, last configured menu affects. <br>
Moha Admin Menu keeps authenticated user with "- No toolbar -" configuration at the end of table to hide Custom Menu Toolbar for logged in user;<br>
instead first configured menu will be used or embedded in amdin_menu. 
INSTRUCTION
    ) . '</div>',
    '#weight' => -99,
  );

  $form = $form_addition + $form;
  $form['#submit'][] = 'moha_admin_menu_custom_menu_toolbar_menu_settings_form_submit';
}

/**
 * @param $form
 * @param $form_state
 *
 * @throws \InvalidMergeQueryException
 */
function moha_admin_menu_custom_menu_toolbar_menu_settings_form_submit(&$form, &$form_state) {
  // Keeps authenticated role with no customized menu and with the highest weight.
  db_merge('custom_menu_toolbar_role_menus')
    //->condition('rid', 2)
    ->key(array(
      'rid' => 2,
    ))
    ->fields(array(
      'menu_name' => '_none',
      'weight' => 999,
    ))
    ->execute();

  // Eliminate original management menu from admin_menu.
  $components = variable_get('admin_menu_components', array());
  $components['admin_menu.menu'] = FALSE;
  variable_set('admin_menu_components', $components);

  // Rebuild admin_menu.
  admin_menu_flush_caches();
}

/**
 * Implements hook_page_build().
 * Inject style to change admin menu background color for non production environment.
 *
 * @inheritdoc
 */
function moha_admin_menu_page_build(&$page) {
  global $base_url; $prefix = substr($base_url, 0, 11 );

  if (moha_cache_get(MOHA_ADMIN_MENU__VARIABLES__NON_PRD)) {
    $page['page_bottom']['#attached']['css'][] = MOHA_ADMIN_MENU__PATH . '/css/moha_admin_menu.non-prd.css';

  }
  elseif (substr($base_url, 0, 11 ) === "http://dev." ||
    substr($base_url, 0, 11 ) === "http://stg." ||
    substr($base_url, 0, 11 ) === "http://stg-" ||
    substr($base_url, 0, 12 ) === "https://stg." ||
    substr($base_url, 0, 12 ) === "https://stg-" ) {

    $page['page_bottom']['#attached']['css'][] = MOHA_ADMIN_MENU__PATH . '/css/moha_admin_menu.non-prd.css';
    moha_cache_set(MOHA_ADMIN_MENU__VARIABLES__NON_PRD, TRUE);
  }
}
