<?php
/**
 * @file
 */

class MohaCommerceOrderEntityAdminController extends EntityDefaultUIController {

  protected function overviewTableHeaders($conditions, $rows, $additional_header = []) {

    $additional_header[] = t('User');
    $additional_header[] = t('Product');
    $additional_header[] = t('Status');
    $additional_header[] = t('Created');

    return parent::overviewTableHeaders($conditions, $rows, $additional_header); // TODO: Change the autogenerated stub
  }


  protected function overviewTableRow($conditions, $id, $entity, $additional_cols = []) {

    $owner = user_load($entity->oid);
    $product = node_load($entity->nid);

    $additional_cols[] = $owner->name;
    $additional_cols[] = $product->title;
    $additional_cols[] = moha_commerce_order_status_array()[$entity->status];
    $additional_cols[] = format_date($product->created, 'short');

    return parent::overviewTableRow($conditions, $id, $entity, $additional_cols);
  }
}
