<?php
/**
 * @file
 */

/**
 *
 */
define('MOHA_DEMO', 'Moha Demo');

/**
 *
 */
define('__MOHA_DEMO', 'moha_demo');

/**
 * sites/all/modules/custom/moha/modules/moha_demo.
 */
define('MOHA_DEMO__RELATIVE_PATH', drupal_get_path('module', __MOHA_DEMO));

/**
 * /sites/all/modules/custom/moha/modules/moha_demo.
 */
define('MOHA_DEMO__PATH', base_path() . MOHA_DEMO__RELATIVE_PATH);

/**
 *
 */
define('MOHA_DEMO__VARIABLES', __MOHA_DEMO. '__variables');

/**
 * Implements hook_menu().
 */
function moha_demo_menu() {

  $items[__MOHA_DEMO. '/web/input'] = [
    'title' => t('Web Demo: Input Box'),
    'description' => t('Style input box'),
    'page callback' => '__moha_demo_web_input',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'file' => 'controllers/demo_web/input.inc',
  ];

  $items[__MOHA_DEMO. '/web/flex'] = [
    'title' => t('Web Demo: Flex'),
    'description' => t('Try flex'),
    'page callback' => '__moha_demo_web_flex',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'file' => 'controllers/demo_web/flex.inc',
  ];

  $items[__MOHA_DEMO. '/web/table-cell'] = [
    'title' => t('Web Demo: table-cell'),
    'description' => t('Try table-cell'),
    'page callback' => '__moha_demo_web',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'file' => 'controllers/demo_web/table_cell.inc',
  ];

  return $items;
}

/**
 * Implements hook_theme().
 */
function moha_demo_theme($existing, $type, $theme, $path) {
  return array(
    // moha_demo_web_input
    __MOHA_DEMO . '_web_input' => array(
      'render element' => 'page',
      'template' => 'templates/demo_web/input',
    ),
    // moha_demo_web_flex
    __MOHA_DEMO . '_web_flex' => array(
      'render element' => 'page',
      'template' => 'templates/demo_web/flex',
    ),
    // moha_demo_web_table_cell
    __MOHA_DEMO . '_web_table_cell' => array(
      'render element' => 'page',
      'template' => 'templates/demo_web/table_cell',
    ),
  );
}
