<?php
/**
 * @file
 */

/**
 * Human name.
 */
define('MOHA_DEMO', 'Moha Demo');

/**
 * Machine name.
 */
define('__MOHA_DEMO', 'moha_demo');

/**
 * sites/all/modules/custom/moha/modules/moha_demo.
 */
define('MOHA_DEMO__PATH', drupal_get_path('module', __MOHA_DEMO));

/**
 * /sites/all/modules/custom/moha/modules/moha_demo.
 */
define('__MOHA_DEMO__PATH', base_path() . MOHA_DEMO__PATH);

/**
 * Module variables name.
 */
define('MOHA_DEMO__VARIABLES', __MOHA_DEMO. '__variables');

/**
 * Implements hook_menu().
 */
function moha_demo_menu() {

  /** @link moha_demo/web/domjs @endlink */
  $items[__MOHA_DEMO. '/web/domjs'] = [
    'title' => t('Web Demo: Dom with Javascript'),
    'description' => t('Style input box'),
    'page callback' => '__moha_demo_domjs',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'file' => 'controllers/moha_demo_web.inc',
  ];

  $items[__MOHA_DEMO. '/web/input'] = [
    'title' => t('Web Demo: Input Box'),
    'description' => t('Style input box'),
    'page callback' => '__moha_demo_web_input',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'file' => 'controllers/demo_web/input.inc',
  ];

  /** @see __moha_demo_web_flex() */
  /** @link moha_demo/web/flex @endlink */
  $items[__MOHA_DEMO. '/web/flex'] = [
    'title' => t('Web Demo: Flex'),
    'description' => t('Try flex'),
    'page callback' => '__moha_demo_web_flex',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'file' => 'controllers/demo_web/flex.inc',
  ];

  $items[__MOHA_DEMO. '/web/table-cell'] = array(
    'title' => t('Web Demo: table-cell'),
    'description' => t('Try table-cell'),
    'page callback' => '__moha_demo_web_table_cell',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'file' => 'controllers/demo_web/table_cell.inc',
  );

  /** @link moha_demo/web/real-time-preview @endlink */
  $items[__MOHA_DEMO. '/web/real-time-preview'] = array(
    'title' => t('Web Demo: real-time preview'),
    'description' => t('Demo real-time preview technology.'),
    /** @see __moha_demo_web_real_time_preview */
    'page callback' => '__moha_demo_web_real_time_preview',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'file' => 'controllers/demo_web/real_time_preview.inc',
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function moha_demo_theme($existing, $type, $theme, $path) {
  $themes = array(
    // Theme name: moha_demo_web_dom_js
    __MOHA_DEMO . '_web_dom_js' => array(
      'render element' => 'content',
      'template' => 'templates/moha_demo_web_dom_js',
    ),
    // moha_demo_web_input
    __MOHA_DEMO . '_web_input' => array(
      'render element' => 'page',
      'template' => 'templates/demo_web/input',
    ),
    // moha_demo_web_flex
    __MOHA_DEMO . '_web_flex' => array(
      'render element' => 'page',
      'template' => 'templates/demo_web/flex',
    ),
    // moha_demo_web_table_cell
    __MOHA_DEMO . '_web_table_cell' => array(
      'render element' => 'page',
      'template' => 'templates/demo_web/table_cell',
    ),
    // moha_demo_real_time_preview
    __MOHA_DEMO . '_web_real_time_preview' => array(
      'render element' => 'page', /* render array will be passed in $page. */
      'template' => 'templates/demo_web/real_time_preview',
    ),
  );

  return $themes;
}
