<?php
/**
 * @file
 */

/**
 * Human name.
 */
define('MOHA_DASHBOARD', 'Moha Dashboard');

/**
 * Machine name.
 */
define('__MOHA_DASHBOARD', 'moha_dashboard');

/**
 * moha_fonts__variables.
 */
define('MOHA_DASHBOARD__VARIABLES', __MOHA_DASHBOARD . '__variables');

/**
 * sites/all/modules/custom/moha/modules/moha_dashboard
 */
define('MOHA_DASHBOARD__RELATIVE_PATH', drupal_get_path('module', __MOHA_DASHBOARD));

/**
 * /sites/all/modules/custom/moha/modules/moha_dashboard
 */
define('MOHA_DASHBOARD__PATH', base_path() . MOHA_DASHBOARD__RELATIVE_PATH);

/**
 * Implements hook_dashboard_regions().
 */
function moha_dashboard_dashboard_regions() {
  // Define a new dashboard region. Your module can also then define
  // theme_mymodule_dashboard_region() as a theme wrapper function to control
  // the region's appearance.
  return array(
    __MOHA_DASHBOARD. '_region_first' => "First " . MOHA_DASHBOARD . " Region",
    __MOHA_DASHBOARD. '_region_second' => "Second " . MOHA_DASHBOARD . " Region",
    __MOHA_DASHBOARD. '_region_third' => "Third " . MOHA_DASHBOARD . " Region",
  );
}

/**
 * Implements hook_dashboard_regions_alter().
 */
function moha_dashboard_dashboard_regions_alter(&$regions) {
  // Remove the sidebar region defined by the core dashboard module.
  unset($regions['dashboard_main']);
  unset($regions['dashboard_sidebar']);
}

/**
 * Returns HTML for a generic dashboard region.
 *
 * @param $variables
 *   An associative array containing:
 *   - element: A render element containing the properties of the dashboard
 *     region element, #dashboard_region and #children.
 *
 * @return string render array with wrapper html
 *
 * @ingroup themeable
 */
function theme_moha_dashboard_region_first($variables) {

  drupal_add_css(MOHA_DASHBOARD__RELATIVE_PATH . '/css/moha_dashboard.css');

  return theme_dashboard_region($variables);
}


/**
 * Implements hook_theme().
 *
 * Declare all theme functions.
 */
function moha_dashboard_theme() {
  return array(
    'moha_dashboard_region_first' => array(
      'render element' => 'element',
    ),
  );
}