<?php
/**
 * @file
 * The hook entry of the module.
 */

/**
 * Human name.
 */
define('MOHA_QR', 'Moha QR');

/**
 * Machine name.
 */
define('__MOHA_QR', 'moha_qr');

/**
 * sites/all/modules/custom/moha/modules/moha_qr.
 */
define('MOHA_QR__PATH', drupal_get_path('module', __MOHA_QR));

/**
 * /sites/all/modules/custom/moha/modules/moha_qr.
 */
define('__MOHA_QR__PATH', base_path() . MOHA_QR__PATH);

/**
 * Implements hook_menu().
 */
function moha_qr_menu() {

  $items['moha/qr/code/%'] = array(
    'title' => 'QR Code',
    'description' => t('QR code generator.'),
    'weight' => 0,
    'page callback' => 'moha_qr_code',
    'page arguments' => array(3),
    'access arguments' => array(MOHA__PERMISSION__ROOT),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * @param $id
 *
 * @link http://phpqrcode.sourceforge.net/examples/index.php @endlink
 * @link https://www.cnblogs.com/yimingwang/p/10027612.html @endlink
 */
function moha_qr_code($id) {
  require_once DRUPAL_ROOT . '/' . MOHA_QR__PATH . '/libs/phpqrcode/phpqrcode.php';

  QRcode::png(MOHA_QR);
}

/**
 * Implements hook_moha_ui_dashboard_sidebar().
 */
function moha_qr_moha_ui_dashboard_sidebar() {
  $items['features']['admin/moha/dashboard/qr'] = array(
    '#markup' => l('<i class="fa fa-qrcode"></i> <span>' . t('QR Code') . '</span>', 'admin/moha/dashboard/qr', array('html' => TRUE)),
    '#weight' => 0,
  );

  return $items;
}






