<?php

/**
 * Human name.
 */
define('MOHA_QR', 'Moha QR');

/**
 * Machine name.
 */
define('__MOHA_QR', 'moha_qr');

/**
 * sites/all/modules/custom/moha/modules/moha_qr.
 */
define('MOHA_QR__PATH', drupal_get_path('module', __MOHA_QR));

/**
 * /sites/all/modules/custom/moha/modules/moha_qr.
 */
define('__MOHA_QR__PATH', base_path() . MOHA_QR__PATH);

/**
 * Implements hook_menu().
 */
function moha_qr_menu() {

  $items[__MOHA . '/qr/list'] = array(

  );

  $items[__MOHA . '/qr/detail/%node'] = array(
    'title' => t('Web Demo: Input Box'),
    'description' => t('Style input box'),
    'page callback' => '__moha_demo_web_input',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}









